/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/projects": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["projects.list"]
    put?: never
    post: operations["projects.create"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/projects/{id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["projects.get"]
    put?: never
    post?: never
    delete: operations["projects.remove"]
    options?: never
    head?: never
    patch: operations["projects.update"]
    trace?: never
  }
  "/api/tasks": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["tasks.list"]
    put?: never
    post: operations["tasks.create"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/tasks/{id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["tasks.get"]
    put?: never
    post?: never
    delete: operations["tasks.remove"]
    options?: never
    head?: never
    patch: operations["tasks.update"]
    trace?: never
  }
  "/api/tasks/resolve/{ref}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["tasks.resolve"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/tasks/{id}/move": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations["tasks.move"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/docs": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["docs.list"]
    put?: never
    post: operations["docs.create"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/docs/{id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["docs.get"]
    put?: never
    post?: never
    delete: operations["docs.remove"]
    options?: never
    head?: never
    patch: operations["docs.update"]
    trace?: never
  }
  "/api/labels": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["labels.list"]
    put?: never
    post: operations["labels.create"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/labels/{id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete: operations["labels.remove"]
    options?: never
    head?: never
    patch: operations["labels.update"]
    trace?: never
  }
  "/api/comments": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["comments.list"]
    put?: never
    post: operations["comments.create"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/comments/{id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete: operations["comments.remove"]
    options?: never
    head?: never
    patch: operations["comments.update"]
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    Unauthorized: {
      /** @enum {string} */
      _tag: "Unauthorized"
      reason: string
    }
    Forbidden: {
      /** @enum {string} */
      _tag: "Forbidden"
      reason: string
    }
    NotFound: {
      /** @enum {string} */
      _tag: "NotFound"
      reason: string
    }
    Conflict: {
      /** @enum {string} */
      _tag: "Conflict"
      reason: string
    }
    InvalidInput: {
      /** @enum {string} */
      _tag: "InvalidInput"
      reason: string
    }
    StorageError: {
      /** @enum {string} */
      _tag: "StorageError"
      reason: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  "projects.list": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            id: string
            key: string
            name: string
            description: string
            /** @enum {string} */
            color:
              | "gray"
              | "blue"
              | "indigo"
              | "purple"
              | "pink"
              | "red"
              | "orange"
              | "amber"
              | "green"
              | "teal"
            archived: boolean
            createdAt: string
            updatedAt: string
          }[]
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Unauthorized"]
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Forbidden"]
        }
      }
      /** @description NotFound */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["NotFound"]
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Conflict"]
        }
      }
      /** @description InvalidInput */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InvalidInput"]
        }
      }
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StorageError"]
        }
      }
    }
  }
  "projects.create": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": {
          name: string
          key?: string
          description?: string
          /** @enum {string} */
          color?:
            | "gray"
            | "blue"
            | "indigo"
            | "purple"
            | "pink"
            | "red"
            | "orange"
            | "amber"
            | "green"
            | "teal"
        }
      }
    }
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            id: string
            key: string
            name: string
            description: string
            /** @enum {string} */
            color:
              | "gray"
              | "blue"
              | "indigo"
              | "purple"
              | "pink"
              | "red"
              | "orange"
              | "amber"
              | "green"
              | "teal"
            archived: boolean
            createdAt: string
            updatedAt: string
          }
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Unauthorized"]
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Forbidden"]
        }
      }
      /** @description NotFound */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["NotFound"]
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Conflict"]
        }
      }
      /** @description InvalidInput */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InvalidInput"]
        }
      }
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StorageError"]
        }
      }
    }
  }
  "projects.get": {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            id: string
            key: string
            name: string
            description: string
            /** @enum {string} */
            color:
              | "gray"
              | "blue"
              | "indigo"
              | "purple"
              | "pink"
              | "red"
              | "orange"
              | "amber"
              | "green"
              | "teal"
            archived: boolean
            createdAt: string
            updatedAt: string
          }
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Unauthorized"]
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Forbidden"]
        }
      }
      /** @description NotFound */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["NotFound"]
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Conflict"]
        }
      }
      /** @description InvalidInput */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InvalidInput"]
        }
      }
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StorageError"]
        }
      }
    }
  }
  "projects.remove": {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            ok: boolean
          }
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Unauthorized"]
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Forbidden"]
        }
      }
      /** @description NotFound */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["NotFound"]
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Conflict"]
        }
      }
      /** @description InvalidInput */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InvalidInput"]
        }
      }
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StorageError"]
        }
      }
    }
  }
  "projects.update": {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": {
          name?: string
          key?: string
          description?: string
          /** @enum {string} */
          color?:
            | "gray"
            | "blue"
            | "indigo"
            | "purple"
            | "pink"
            | "red"
            | "orange"
            | "amber"
            | "green"
            | "teal"
          archived?: boolean
        }
      }
    }
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            id: string
            key: string
            name: string
            description: string
            /** @enum {string} */
            color:
              | "gray"
              | "blue"
              | "indigo"
              | "purple"
              | "pink"
              | "red"
              | "orange"
              | "amber"
              | "green"
              | "teal"
            archived: boolean
            createdAt: string
            updatedAt: string
          }
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Unauthorized"]
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Forbidden"]
        }
      }
      /** @description NotFound */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["NotFound"]
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Conflict"]
        }
      }
      /** @description InvalidInput */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InvalidInput"]
        }
      }
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StorageError"]
        }
      }
    }
  }
  "tasks.list": {
    parameters: {
      query: {
        projectId: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            id: string
            projectId: string
            number: number
            key: string
            title: string
            description: string
            /** @enum {string} */
            status:
              | "backlog"
              | "todo"
              | "in_progress"
              | "in_review"
              | "paused"
              | "done"
              | "canceled"
            /** @enum {string} */
            priority: "none" | "low" | "medium" | "high" | "urgent"
            parentId: string | null
            position: number
            labelIds: string[]
            createdAt: string
            updatedAt: string
            completedAt: string | null
          }[]
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Unauthorized"]
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Forbidden"]
        }
      }
      /** @description NotFound */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["NotFound"]
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Conflict"]
        }
      }
      /** @description InvalidInput */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InvalidInput"]
        }
      }
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StorageError"]
        }
      }
    }
  }
  "tasks.create": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": {
          projectId: string
          title: string
          description?: string
          /** @enum {string} */
          status?:
            | "backlog"
            | "todo"
            | "in_progress"
            | "in_review"
            | "paused"
            | "done"
            | "canceled"
          /** @enum {string} */
          priority?: "none" | "low" | "medium" | "high" | "urgent"
          parentId?: string | null
          labelIds?: string[]
        }
      }
    }
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            id: string
            projectId: string
            number: number
            key: string
            title: string
            description: string
            /** @enum {string} */
            status:
              | "backlog"
              | "todo"
              | "in_progress"
              | "in_review"
              | "paused"
              | "done"
              | "canceled"
            /** @enum {string} */
            priority: "none" | "low" | "medium" | "high" | "urgent"
            parentId: string | null
            position: number
            labelIds: string[]
            createdAt: string
            updatedAt: string
            completedAt: string | null
          }
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Unauthorized"]
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Forbidden"]
        }
      }
      /** @description NotFound */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["NotFound"]
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Conflict"]
        }
      }
      /** @description InvalidInput */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InvalidInput"]
        }
      }
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StorageError"]
        }
      }
    }
  }
  "tasks.get": {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            id: string
            projectId: string
            number: number
            key: string
            title: string
            description: string
            /** @enum {string} */
            status:
              | "backlog"
              | "todo"
              | "in_progress"
              | "in_review"
              | "paused"
              | "done"
              | "canceled"
            /** @enum {string} */
            priority: "none" | "low" | "medium" | "high" | "urgent"
            parentId: string | null
            position: number
            labelIds: string[]
            createdAt: string
            updatedAt: string
            completedAt: string | null
          }
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Unauthorized"]
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Forbidden"]
        }
      }
      /** @description NotFound */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["NotFound"]
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Conflict"]
        }
      }
      /** @description InvalidInput */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InvalidInput"]
        }
      }
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StorageError"]
        }
      }
    }
  }
  "tasks.remove": {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            ok: boolean
          }
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Unauthorized"]
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Forbidden"]
        }
      }
      /** @description NotFound */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["NotFound"]
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Conflict"]
        }
      }
      /** @description InvalidInput */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InvalidInput"]
        }
      }
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StorageError"]
        }
      }
    }
  }
  "tasks.update": {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": {
          title?: string
          description?: string
          /** @enum {string} */
          status?:
            | "backlog"
            | "todo"
            | "in_progress"
            | "in_review"
            | "paused"
            | "done"
            | "canceled"
          /** @enum {string} */
          priority?: "none" | "low" | "medium" | "high" | "urgent"
          parentId?: string | null
          position?: number
          labelIds?: string[]
        }
      }
    }
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            id: string
            projectId: string
            number: number
            key: string
            title: string
            description: string
            /** @enum {string} */
            status:
              | "backlog"
              | "todo"
              | "in_progress"
              | "in_review"
              | "paused"
              | "done"
              | "canceled"
            /** @enum {string} */
            priority: "none" | "low" | "medium" | "high" | "urgent"
            parentId: string | null
            position: number
            labelIds: string[]
            createdAt: string
            updatedAt: string
            completedAt: string | null
          }
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Unauthorized"]
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Forbidden"]
        }
      }
      /** @description NotFound */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["NotFound"]
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Conflict"]
        }
      }
      /** @description InvalidInput */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InvalidInput"]
        }
      }
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StorageError"]
        }
      }
    }
  }
  "tasks.resolve": {
    parameters: {
      query?: never
      header?: never
      path: {
        ref: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            id: string
            projectId: string
            number: number
            key: string
            title: string
            description: string
            /** @enum {string} */
            status:
              | "backlog"
              | "todo"
              | "in_progress"
              | "in_review"
              | "paused"
              | "done"
              | "canceled"
            /** @enum {string} */
            priority: "none" | "low" | "medium" | "high" | "urgent"
            parentId: string | null
            position: number
            labelIds: string[]
            createdAt: string
            updatedAt: string
            completedAt: string | null
          }
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Unauthorized"]
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Forbidden"]
        }
      }
      /** @description NotFound */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["NotFound"]
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Conflict"]
        }
      }
      /** @description InvalidInput */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InvalidInput"]
        }
      }
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StorageError"]
        }
      }
    }
  }
  "tasks.move": {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": {
          /** @enum {string} */
          status:
            | "backlog"
            | "todo"
            | "in_progress"
            | "in_review"
            | "paused"
            | "done"
            | "canceled"
          index: number
        }
      }
    }
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            id: string
            projectId: string
            number: number
            key: string
            title: string
            description: string
            /** @enum {string} */
            status:
              | "backlog"
              | "todo"
              | "in_progress"
              | "in_review"
              | "paused"
              | "done"
              | "canceled"
            /** @enum {string} */
            priority: "none" | "low" | "medium" | "high" | "urgent"
            parentId: string | null
            position: number
            labelIds: string[]
            createdAt: string
            updatedAt: string
            completedAt: string | null
          }
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Unauthorized"]
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Forbidden"]
        }
      }
      /** @description NotFound */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["NotFound"]
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Conflict"]
        }
      }
      /** @description InvalidInput */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InvalidInput"]
        }
      }
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StorageError"]
        }
      }
    }
  }
  "docs.list": {
    parameters: {
      query: {
        projectId: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            id: string
            projectId: string
            title: string
            updatedAt: string
          }[]
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Unauthorized"]
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Forbidden"]
        }
      }
      /** @description NotFound */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["NotFound"]
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Conflict"]
        }
      }
      /** @description InvalidInput */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InvalidInput"]
        }
      }
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StorageError"]
        }
      }
    }
  }
  "docs.create": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": {
          projectId: string
          title?: string
          content?: string
        }
      }
    }
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            id: string
            projectId: string
            title: string
            content: string
            createdAt: string
            updatedAt: string
          }
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Unauthorized"]
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Forbidden"]
        }
      }
      /** @description NotFound */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["NotFound"]
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Conflict"]
        }
      }
      /** @description InvalidInput */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InvalidInput"]
        }
      }
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StorageError"]
        }
      }
    }
  }
  "docs.get": {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            id: string
            projectId: string
            title: string
            content: string
            createdAt: string
            updatedAt: string
          }
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Unauthorized"]
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Forbidden"]
        }
      }
      /** @description NotFound */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["NotFound"]
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Conflict"]
        }
      }
      /** @description InvalidInput */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InvalidInput"]
        }
      }
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StorageError"]
        }
      }
    }
  }
  "docs.remove": {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            ok: boolean
          }
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Unauthorized"]
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Forbidden"]
        }
      }
      /** @description NotFound */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["NotFound"]
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Conflict"]
        }
      }
      /** @description InvalidInput */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InvalidInput"]
        }
      }
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StorageError"]
        }
      }
    }
  }
  "docs.update": {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": {
          title?: string
          content?: string
        }
      }
    }
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            id: string
            projectId: string
            title: string
            content: string
            createdAt: string
            updatedAt: string
          }
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Unauthorized"]
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Forbidden"]
        }
      }
      /** @description NotFound */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["NotFound"]
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Conflict"]
        }
      }
      /** @description InvalidInput */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InvalidInput"]
        }
      }
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StorageError"]
        }
      }
    }
  }
  "labels.list": {
    parameters: {
      query: {
        projectId: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            id: string
            projectId: string
            name: string
            /** @enum {string} */
            color:
              | "gray"
              | "blue"
              | "indigo"
              | "purple"
              | "pink"
              | "red"
              | "orange"
              | "amber"
              | "green"
              | "teal"
            createdAt: string
          }[]
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Unauthorized"]
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Forbidden"]
        }
      }
      /** @description NotFound */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["NotFound"]
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Conflict"]
        }
      }
      /** @description InvalidInput */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InvalidInput"]
        }
      }
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StorageError"]
        }
      }
    }
  }
  "labels.create": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": {
          projectId: string
          name: string
          /** @enum {string} */
          color?:
            | "gray"
            | "blue"
            | "indigo"
            | "purple"
            | "pink"
            | "red"
            | "orange"
            | "amber"
            | "green"
            | "teal"
        }
      }
    }
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            id: string
            projectId: string
            name: string
            /** @enum {string} */
            color:
              | "gray"
              | "blue"
              | "indigo"
              | "purple"
              | "pink"
              | "red"
              | "orange"
              | "amber"
              | "green"
              | "teal"
            createdAt: string
          }
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Unauthorized"]
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Forbidden"]
        }
      }
      /** @description NotFound */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["NotFound"]
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Conflict"]
        }
      }
      /** @description InvalidInput */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InvalidInput"]
        }
      }
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StorageError"]
        }
      }
    }
  }
  "labels.remove": {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            ok: boolean
          }
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Unauthorized"]
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Forbidden"]
        }
      }
      /** @description NotFound */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["NotFound"]
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Conflict"]
        }
      }
      /** @description InvalidInput */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InvalidInput"]
        }
      }
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StorageError"]
        }
      }
    }
  }
  "labels.update": {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": {
          name?: string
          /** @enum {string} */
          color?:
            | "gray"
            | "blue"
            | "indigo"
            | "purple"
            | "pink"
            | "red"
            | "orange"
            | "amber"
            | "green"
            | "teal"
        }
      }
    }
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            id: string
            projectId: string
            name: string
            /** @enum {string} */
            color:
              | "gray"
              | "blue"
              | "indigo"
              | "purple"
              | "pink"
              | "red"
              | "orange"
              | "amber"
              | "green"
              | "teal"
            createdAt: string
          }
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Unauthorized"]
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Forbidden"]
        }
      }
      /** @description NotFound */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["NotFound"]
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Conflict"]
        }
      }
      /** @description InvalidInput */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InvalidInput"]
        }
      }
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StorageError"]
        }
      }
    }
  }
  "comments.list": {
    parameters: {
      query: {
        subjectType: "task" | "doc"
        subjectId: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            id: string
            /** @enum {string} */
            subjectType: "task" | "doc"
            subjectId: string
            parentId: string | null
            body: string
            author: {
              id: string
              name: string
              email: string
              image: string | null
            }
            createdAt: string
            updatedAt: string
            edited: boolean
          }[]
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Unauthorized"]
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Forbidden"]
        }
      }
      /** @description NotFound */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["NotFound"]
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Conflict"]
        }
      }
      /** @description InvalidInput */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InvalidInput"]
        }
      }
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StorageError"]
        }
      }
    }
  }
  "comments.create": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": {
          /** @enum {string} */
          subjectType: "task" | "doc"
          subjectId: string
          body: string
          parentId?: string | null
        }
      }
    }
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            id: string
            /** @enum {string} */
            subjectType: "task" | "doc"
            subjectId: string
            parentId: string | null
            body: string
            author: {
              id: string
              name: string
              email: string
              image: string | null
            }
            createdAt: string
            updatedAt: string
            edited: boolean
          }
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Unauthorized"]
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Forbidden"]
        }
      }
      /** @description NotFound */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["NotFound"]
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Conflict"]
        }
      }
      /** @description InvalidInput */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InvalidInput"]
        }
      }
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StorageError"]
        }
      }
    }
  }
  "comments.remove": {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            ok: boolean
          }
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Unauthorized"]
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Forbidden"]
        }
      }
      /** @description NotFound */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["NotFound"]
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Conflict"]
        }
      }
      /** @description InvalidInput */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InvalidInput"]
        }
      }
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StorageError"]
        }
      }
    }
  }
  "comments.update": {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": {
          body: string
        }
      }
    }
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            id: string
            /** @enum {string} */
            subjectType: "task" | "doc"
            subjectId: string
            parentId: string | null
            body: string
            author: {
              id: string
              name: string
              email: string
              image: string | null
            }
            createdAt: string
            updatedAt: string
            edited: boolean
          }
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Unauthorized"]
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Forbidden"]
        }
      }
      /** @description NotFound */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["NotFound"]
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Conflict"]
        }
      }
      /** @description InvalidInput */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InvalidInput"]
        }
      }
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StorageError"]
        }
      }
    }
  }
}
