/**
 * git-message service — drafts a commit message for the working changes by
 * handing the diff to one of the user's locally installed agent CLIs
 * (`claude -p`, `opencode run`, `codex exec`). It composes GitExec for the diff
 * and branch, and TerminalExec to run the chosen agent through the user's login
 * shell so the CLI resolves on PATH exactly like it does in a real terminal.
 */
import * as Context from "effect/Context"
import * as Effect from "effect/Effect"
import { agentCommand } from "../../threads/agents.ts"
import { TerminalError } from "../../../layers/errors.ts"
import type { GitFailure } from "../../../layers/git/git-exec.ts"
import { GitExec } from "../../../layers/git/git-exec.ts"
import { TerminalExec } from "../../../layers/terminal/terminal-exec.ts"
import type { CommitAgent } from "@byconvo/models/git-message"

/** Cap the diff so the prompt stays small and the call returns quickly. */
const MAX_DIFF_CHARS = 16_000

/** The agent used when the caller doesn't pick one. */
export const DEFAULT_COMMIT_AGENT: CommitAgent = "claude"

/**
 * Pull an issue slug like `DAR-144` / `ABC-7` out of a branch name (e.g.
 * `feature/DAR-144-add-thing` → `DAR-144`). Returns null when there is none.
 */
const branchSlug = (branch: string): string | null => {
  const match = branch.match(/[A-Z][A-Z0-9]*-\d+/)
  return match?.[0] ?? null
}

/** Build the model prompt for the given changes and optional issue slug. */
const buildPrompt = (changes: string, slug: string | null): string =>
  [
    "Generate a git commit message for the changes below.",
    "",
    "Rules:",
    "- First line: a concise, descriptive title summarizing the change.",
    "- Then a blank line, then bullet points (each starting with '- ')",
    "  describing the notable changes.",
    "- Be descriptive and factual. Do not be flamboyant or use marketing language.",
    '- Do NOT include any attribution ("Generated by", "Co-Authored-By", tool or',
    "  model names).",
    "- Do NOT add a Conventional Commits prefix (no feat:/fix:/chore:/refactor:/etc.).",
    slug !== null
      ? `- Begin the title with "${slug} " (the issue slug), then the summary.`
      : "- Do not add any prefix to the title.",
    "",
    "Output ONLY the raw commit message — no surrounding quotes, no markdown code",
    "fences, no preamble or sign-off.",
    "",
    "--- CHANGES ---",
    changes,
  ].join("\n")

/** Strip code fences or wrapping single/double quotes a model may add anyway. */
const cleanMessage = (raw: string): string => {
  let text = raw.trim()
  const fence = text.match(/^```[^\n]*\n([\s\S]*?)\n```$/)
  if (fence?.[1] !== undefined) text = fence[1].trim()
  if (
    text.length >= 2 &&
    ((text.startsWith('"') && text.endsWith('"')) ||
      (text.startsWith("'") && text.endsWith("'")))
  ) {
    text = text.slice(1, -1).trim()
  }
  return text
}

export interface GitMessageServiceShape {
  readonly generate: (
    paths: ReadonlyArray<string>,
    agent: CommitAgent
  ) => Effect.Effect<string, GitFailure | TerminalError>
}

export class GitMessageService extends Context.Service<
  GitMessageService,
  GitMessageServiceShape
>()("GitMessageService") {}

export const make = Effect.gen(function* () {
  const { lines, run } = yield* GitExec
  const terminal = yield* TerminalExec

  const generate: GitMessageServiceShape["generate"] = (paths, agent) =>
    Effect.gen(function* () {
      // Working-tree diff vs HEAD for the chosen paths (empty = everything).
      // Tolerate failures (e.g. unborn HEAD) by falling back to an empty diff.
      const diff = yield* run(
        ...(paths.length === 0
          ? ["diff", "HEAD"]
          : ["diff", "HEAD", "--", ...paths])
      ).pipe(Effect.catchTag("GitError", () => Effect.succeed("")))

      // git diff omits untracked files; name them so the agent knows they're new.
      const untracked = yield* lines(
        ...(paths.length === 0
          ? ["ls-files", "--others", "--exclude-standard"]
          : ["ls-files", "--others", "--exclude-standard", "--", ...paths])
      ).pipe(Effect.catchTag("GitError", () => Effect.succeed([] as const)))

      const truncated =
        diff.length > MAX_DIFF_CHARS
          ? `${diff.slice(0, MAX_DIFF_CHARS)}\n…[diff truncated]`
          : diff
      const newFiles =
        untracked.length > 0
          ? `\n\nNew untracked files:\n${untracked.map((f) => `  ${f}`).join("\n")}`
          : ""
      const changes = `${truncated}${newFiles}`.trim()

      if (changes.length === 0) {
        return yield* Effect.fail(
          new TerminalError({ reason: "no changes to summarize" })
        )
      }

      // Prepend the branch's issue slug (e.g. DAR-144) when there is one.
      const branch = yield* run("rev-parse", "--abbrev-ref", "HEAD").pipe(
        Effect.map((b) => b.trim()),
        Effect.catchTag("GitError", () => Effect.succeed(""))
      )

      const prompt = buildPrompt(changes, branchSlug(branch))
      const { stdout, stderr, exitCode } = yield* terminal.run(
        agentCommand(agent, prompt)
      )
      if (exitCode !== 0) {
        const reason = stderr.trim()
        return yield* Effect.fail(
          new TerminalError({
            reason:
              reason.length > 0
                ? `the "${agent}" CLI exited ${exitCode}: ${reason}`
                : `the "${agent}" CLI exited ${exitCode} — is it installed and on your PATH?`,
          })
        )
      }
      const message = cleanMessage(stdout)
      return message.length > 0
        ? message
        : yield* Effect.fail(
            new TerminalError({
              reason: `the "${agent}" CLI produced no commit message`,
            })
          )
    })

  return GitMessageService.of({ generate })
})
