/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as KitchenSinkRouteImport } from './routes/kitchen-sink'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppModesAgentSessionRouteImport } from './routes/_app/modes.agent-session'
import { Route as AppModesCollaborationRouteImport } from './routes/_app/modes.collaboration'
import { Route as AppModesAgentSessionIndexRouteImport } from './routes/_app/modes.agent-session.index'
import { Route as AppModesAgentSessionChatIdRouteImport } from './routes/_app/modes.agent-session.$chatId'
import { Route as AppModesCodeIndexRouteImport } from './routes/_app/modes.code.index'
import { Route as AppModesCodeBranchesRouteImport } from './routes/_app/modes.code.branches'
import { Route as AppModesCodeCommitRouteImport } from './routes/_app/modes.code.commit'
import { Route as AppModesCodeDocsRouteImport } from './routes/_app/modes.code.docs'
import { Route as AppModesCodeHistoryRouteImport } from './routes/_app/modes.code.history'
import { Route as AppModesCodeLocalDevRouteImport } from './routes/_app/modes.code.local-dev'
import { Route as AppModesCodeTasksRouteImport } from './routes/_app/modes.code.tasks'
import { Route as AppModesCodeThreadsRouteImport } from './routes/_app/modes.code.threads'
import { Route as AppModesCollaborationInboxRouteImport } from './routes/_app/modes.collaboration_.inbox'
import { Route as AppModesCodeBrowseIndexRouteImport } from './routes/_app/modes.code.browse.index'
import { Route as AppModesCodeBrowseRangeRouteImport } from './routes/_app/modes.code.browse.range'
import { Route as AppModesCodeReviewIndexRouteImport } from './routes/_app/modes.code.review.index'
import { Route as AppModesCodeReviewPullRouteImport } from './routes/_app/modes.code.review.$pull'
import { Route as AppModesCodeBrowseCommitShaRouteImport } from './routes/_app/modes.code.browse.commit.$sha'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenSinkRoute = KitchenSinkRouteImport.update({
  id: '/kitchen-sink',
  path: '/kitchen-sink',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppModesAgentSessionRoute = AppModesAgentSessionRouteImport.update({
  id: '/modes/agent-session',
  path: '/modes/agent-session',
  getParentRoute: () => AppRoute,
} as any)
const AppModesCollaborationRoute = AppModesCollaborationRouteImport.update({
  id: '/modes/collaboration',
  path: '/modes/collaboration',
  getParentRoute: () => AppRoute,
} as any)
const AppModesAgentSessionIndexRoute =
  AppModesAgentSessionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppModesAgentSessionRoute,
  } as any)
const AppModesAgentSessionChatIdRoute =
  AppModesAgentSessionChatIdRouteImport.update({
    id: '/$chatId',
    path: '/$chatId',
    getParentRoute: () => AppModesAgentSessionRoute,
  } as any)
const AppModesCodeIndexRoute = AppModesCodeIndexRouteImport.update({
  id: '/modes/code/',
  path: '/modes/code/',
  getParentRoute: () => AppRoute,
} as any)
const AppModesCodeBranchesRoute = AppModesCodeBranchesRouteImport.update({
  id: '/modes/code/branches',
  path: '/modes/code/branches',
  getParentRoute: () => AppRoute,
} as any)
const AppModesCodeCommitRoute = AppModesCodeCommitRouteImport.update({
  id: '/modes/code/commit',
  path: '/modes/code/commit',
  getParentRoute: () => AppRoute,
} as any)
const AppModesCodeDocsRoute = AppModesCodeDocsRouteImport.update({
  id: '/modes/code/docs',
  path: '/modes/code/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppModesCodeHistoryRoute = AppModesCodeHistoryRouteImport.update({
  id: '/modes/code/history',
  path: '/modes/code/history',
  getParentRoute: () => AppRoute,
} as any)
const AppModesCodeLocalDevRoute = AppModesCodeLocalDevRouteImport.update({
  id: '/modes/code/local-dev',
  path: '/modes/code/local-dev',
  getParentRoute: () => AppRoute,
} as any)
const AppModesCodeTasksRoute = AppModesCodeTasksRouteImport.update({
  id: '/modes/code/tasks',
  path: '/modes/code/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppModesCodeThreadsRoute = AppModesCodeThreadsRouteImport.update({
  id: '/modes/code/threads',
  path: '/modes/code/threads',
  getParentRoute: () => AppRoute,
} as any)
const AppModesCollaborationInboxRoute =
  AppModesCollaborationInboxRouteImport.update({
    id: '/modes/collaboration_/inbox',
    path: '/modes/collaboration/inbox',
    getParentRoute: () => AppRoute,
  } as any)
const AppModesCodeBrowseIndexRoute = AppModesCodeBrowseIndexRouteImport.update({
  id: '/modes/code/browse/',
  path: '/modes/code/browse/',
  getParentRoute: () => AppRoute,
} as any)
const AppModesCodeBrowseRangeRoute = AppModesCodeBrowseRangeRouteImport.update({
  id: '/modes/code/browse/range',
  path: '/modes/code/browse/range',
  getParentRoute: () => AppRoute,
} as any)
const AppModesCodeReviewIndexRoute = AppModesCodeReviewIndexRouteImport.update({
  id: '/modes/code/review/',
  path: '/modes/code/review/',
  getParentRoute: () => AppRoute,
} as any)
const AppModesCodeReviewPullRoute = AppModesCodeReviewPullRouteImport.update({
  id: '/modes/code/review/$pull',
  path: '/modes/code/review/$pull',
  getParentRoute: () => AppRoute,
} as any)
const AppModesCodeBrowseCommitShaRoute =
  AppModesCodeBrowseCommitShaRouteImport.update({
    id: '/modes/code/browse/commit/$sha',
    path: '/modes/code/browse/commit/$sha',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/kitchen-sink': typeof KitchenSinkRoute
  '/settings': typeof AppSettingsRoute
  '/modes/agent-session': typeof AppModesAgentSessionRouteWithChildren
  '/modes/collaboration': typeof AppModesCollaborationRoute
  '/modes/agent-session/$chatId': typeof AppModesAgentSessionChatIdRoute
  '/modes/code/branches': typeof AppModesCodeBranchesRoute
  '/modes/code/commit': typeof AppModesCodeCommitRoute
  '/modes/code/docs': typeof AppModesCodeDocsRoute
  '/modes/code/history': typeof AppModesCodeHistoryRoute
  '/modes/code/local-dev': typeof AppModesCodeLocalDevRoute
  '/modes/code/tasks': typeof AppModesCodeTasksRoute
  '/modes/code/threads': typeof AppModesCodeThreadsRoute
  '/modes/collaboration/inbox': typeof AppModesCollaborationInboxRoute
  '/modes/agent-session/': typeof AppModesAgentSessionIndexRoute
  '/modes/code/': typeof AppModesCodeIndexRoute
  '/modes/code/browse/range': typeof AppModesCodeBrowseRangeRoute
  '/modes/code/review/$pull': typeof AppModesCodeReviewPullRoute
  '/modes/code/browse/': typeof AppModesCodeBrowseIndexRoute
  '/modes/code/review/': typeof AppModesCodeReviewIndexRoute
  '/modes/code/browse/commit/$sha': typeof AppModesCodeBrowseCommitShaRoute
}
export interface FileRoutesByTo {
  '/kitchen-sink': typeof KitchenSinkRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/modes/collaboration': typeof AppModesCollaborationRoute
  '/modes/agent-session/$chatId': typeof AppModesAgentSessionChatIdRoute
  '/modes/code/branches': typeof AppModesCodeBranchesRoute
  '/modes/code/commit': typeof AppModesCodeCommitRoute
  '/modes/code/docs': typeof AppModesCodeDocsRoute
  '/modes/code/history': typeof AppModesCodeHistoryRoute
  '/modes/code/local-dev': typeof AppModesCodeLocalDevRoute
  '/modes/code/tasks': typeof AppModesCodeTasksRoute
  '/modes/code/threads': typeof AppModesCodeThreadsRoute
  '/modes/collaboration/inbox': typeof AppModesCollaborationInboxRoute
  '/modes/agent-session': typeof AppModesAgentSessionIndexRoute
  '/modes/code': typeof AppModesCodeIndexRoute
  '/modes/code/browse/range': typeof AppModesCodeBrowseRangeRoute
  '/modes/code/review/$pull': typeof AppModesCodeReviewPullRoute
  '/modes/code/browse': typeof AppModesCodeBrowseIndexRoute
  '/modes/code/review': typeof AppModesCodeReviewIndexRoute
  '/modes/code/browse/commit/$sha': typeof AppModesCodeBrowseCommitShaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/kitchen-sink': typeof KitchenSinkRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/modes/agent-session': typeof AppModesAgentSessionRouteWithChildren
  '/_app/modes/collaboration': typeof AppModesCollaborationRoute
  '/_app/modes/agent-session/$chatId': typeof AppModesAgentSessionChatIdRoute
  '/_app/modes/code/branches': typeof AppModesCodeBranchesRoute
  '/_app/modes/code/commit': typeof AppModesCodeCommitRoute
  '/_app/modes/code/docs': typeof AppModesCodeDocsRoute
  '/_app/modes/code/history': typeof AppModesCodeHistoryRoute
  '/_app/modes/code/local-dev': typeof AppModesCodeLocalDevRoute
  '/_app/modes/code/tasks': typeof AppModesCodeTasksRoute
  '/_app/modes/code/threads': typeof AppModesCodeThreadsRoute
  '/_app/modes/collaboration_/inbox': typeof AppModesCollaborationInboxRoute
  '/_app/modes/agent-session/': typeof AppModesAgentSessionIndexRoute
  '/_app/modes/code/': typeof AppModesCodeIndexRoute
  '/_app/modes/code/browse/range': typeof AppModesCodeBrowseRangeRoute
  '/_app/modes/code/review/$pull': typeof AppModesCodeReviewPullRoute
  '/_app/modes/code/browse/': typeof AppModesCodeBrowseIndexRoute
  '/_app/modes/code/review/': typeof AppModesCodeReviewIndexRoute
  '/_app/modes/code/browse/commit/$sha': typeof AppModesCodeBrowseCommitShaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kitchen-sink'
    | '/settings'
    | '/modes/agent-session'
    | '/modes/collaboration'
    | '/modes/agent-session/$chatId'
    | '/modes/code/branches'
    | '/modes/code/commit'
    | '/modes/code/docs'
    | '/modes/code/history'
    | '/modes/code/local-dev'
    | '/modes/code/tasks'
    | '/modes/code/threads'
    | '/modes/collaboration/inbox'
    | '/modes/agent-session/'
    | '/modes/code/'
    | '/modes/code/browse/range'
    | '/modes/code/review/$pull'
    | '/modes/code/browse/'
    | '/modes/code/review/'
    | '/modes/code/browse/commit/$sha'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/kitchen-sink'
    | '/settings'
    | '/'
    | '/modes/collaboration'
    | '/modes/agent-session/$chatId'
    | '/modes/code/branches'
    | '/modes/code/commit'
    | '/modes/code/docs'
    | '/modes/code/history'
    | '/modes/code/local-dev'
    | '/modes/code/tasks'
    | '/modes/code/threads'
    | '/modes/collaboration/inbox'
    | '/modes/agent-session'
    | '/modes/code'
    | '/modes/code/browse/range'
    | '/modes/code/review/$pull'
    | '/modes/code/browse'
    | '/modes/code/review'
    | '/modes/code/browse/commit/$sha'
  id:
    | '__root__'
    | '/_app'
    | '/kitchen-sink'
    | '/_app/settings'
    | '/_app/'
    | '/_app/modes/agent-session'
    | '/_app/modes/collaboration'
    | '/_app/modes/agent-session/$chatId'
    | '/_app/modes/code/branches'
    | '/_app/modes/code/commit'
    | '/_app/modes/code/docs'
    | '/_app/modes/code/history'
    | '/_app/modes/code/local-dev'
    | '/_app/modes/code/tasks'
    | '/_app/modes/code/threads'
    | '/_app/modes/collaboration_/inbox'
    | '/_app/modes/agent-session/'
    | '/_app/modes/code/'
    | '/_app/modes/code/browse/range'
    | '/_app/modes/code/review/$pull'
    | '/_app/modes/code/browse/'
    | '/_app/modes/code/review/'
    | '/_app/modes/code/browse/commit/$sha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  KitchenSinkRoute: typeof KitchenSinkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-sink': {
      id: '/kitchen-sink'
      path: '/kitchen-sink'
      fullPath: '/kitchen-sink'
      preLoaderRoute: typeof KitchenSinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modes/agent-session': {
      id: '/_app/modes/agent-session'
      path: '/modes/agent-session'
      fullPath: '/modes/agent-session'
      preLoaderRoute: typeof AppModesAgentSessionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modes/collaboration': {
      id: '/_app/modes/collaboration'
      path: '/modes/collaboration'
      fullPath: '/modes/collaboration'
      preLoaderRoute: typeof AppModesCollaborationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modes/agent-session/': {
      id: '/_app/modes/agent-session/'
      path: '/'
      fullPath: '/modes/agent-session/'
      preLoaderRoute: typeof AppModesAgentSessionIndexRouteImport
      parentRoute: typeof AppModesAgentSessionRoute
    }
    '/_app/modes/agent-session/$chatId': {
      id: '/_app/modes/agent-session/$chatId'
      path: '/$chatId'
      fullPath: '/modes/agent-session/$chatId'
      preLoaderRoute: typeof AppModesAgentSessionChatIdRouteImport
      parentRoute: typeof AppModesAgentSessionRoute
    }
    '/_app/modes/code/': {
      id: '/_app/modes/code/'
      path: '/modes/code'
      fullPath: '/modes/code/'
      preLoaderRoute: typeof AppModesCodeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modes/code/branches': {
      id: '/_app/modes/code/branches'
      path: '/modes/code/branches'
      fullPath: '/modes/code/branches'
      preLoaderRoute: typeof AppModesCodeBranchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modes/code/commit': {
      id: '/_app/modes/code/commit'
      path: '/modes/code/commit'
      fullPath: '/modes/code/commit'
      preLoaderRoute: typeof AppModesCodeCommitRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modes/code/docs': {
      id: '/_app/modes/code/docs'
      path: '/modes/code/docs'
      fullPath: '/modes/code/docs'
      preLoaderRoute: typeof AppModesCodeDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modes/code/history': {
      id: '/_app/modes/code/history'
      path: '/modes/code/history'
      fullPath: '/modes/code/history'
      preLoaderRoute: typeof AppModesCodeHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modes/code/local-dev': {
      id: '/_app/modes/code/local-dev'
      path: '/modes/code/local-dev'
      fullPath: '/modes/code/local-dev'
      preLoaderRoute: typeof AppModesCodeLocalDevRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modes/code/tasks': {
      id: '/_app/modes/code/tasks'
      path: '/modes/code/tasks'
      fullPath: '/modes/code/tasks'
      preLoaderRoute: typeof AppModesCodeTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modes/code/threads': {
      id: '/_app/modes/code/threads'
      path: '/modes/code/threads'
      fullPath: '/modes/code/threads'
      preLoaderRoute: typeof AppModesCodeThreadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modes/collaboration_/inbox': {
      id: '/_app/modes/collaboration_/inbox'
      path: '/modes/collaboration/inbox'
      fullPath: '/modes/collaboration/inbox'
      preLoaderRoute: typeof AppModesCollaborationInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modes/code/browse/': {
      id: '/_app/modes/code/browse/'
      path: '/modes/code/browse'
      fullPath: '/modes/code/browse/'
      preLoaderRoute: typeof AppModesCodeBrowseIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modes/code/browse/range': {
      id: '/_app/modes/code/browse/range'
      path: '/modes/code/browse/range'
      fullPath: '/modes/code/browse/range'
      preLoaderRoute: typeof AppModesCodeBrowseRangeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modes/code/review/': {
      id: '/_app/modes/code/review/'
      path: '/modes/code/review'
      fullPath: '/modes/code/review/'
      preLoaderRoute: typeof AppModesCodeReviewIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modes/code/review/$pull': {
      id: '/_app/modes/code/review/$pull'
      path: '/modes/code/review/$pull'
      fullPath: '/modes/code/review/$pull'
      preLoaderRoute: typeof AppModesCodeReviewPullRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modes/code/browse/commit/$sha': {
      id: '/_app/modes/code/browse/commit/$sha'
      path: '/modes/code/browse/commit/$sha'
      fullPath: '/modes/code/browse/commit/$sha'
      preLoaderRoute: typeof AppModesCodeBrowseCommitShaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppModesAgentSessionRouteChildren {
  AppModesAgentSessionChatIdRoute: typeof AppModesAgentSessionChatIdRoute
  AppModesAgentSessionIndexRoute: typeof AppModesAgentSessionIndexRoute
}

const AppModesAgentSessionRouteChildren: AppModesAgentSessionRouteChildren = {
  AppModesAgentSessionChatIdRoute: AppModesAgentSessionChatIdRoute,
  AppModesAgentSessionIndexRoute: AppModesAgentSessionIndexRoute,
}

const AppModesAgentSessionRouteWithChildren =
  AppModesAgentSessionRoute._addFileChildren(AppModesAgentSessionRouteChildren)

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppModesAgentSessionRoute: typeof AppModesAgentSessionRouteWithChildren
  AppModesCollaborationRoute: typeof AppModesCollaborationRoute
  AppModesCodeBranchesRoute: typeof AppModesCodeBranchesRoute
  AppModesCodeCommitRoute: typeof AppModesCodeCommitRoute
  AppModesCodeDocsRoute: typeof AppModesCodeDocsRoute
  AppModesCodeHistoryRoute: typeof AppModesCodeHistoryRoute
  AppModesCodeLocalDevRoute: typeof AppModesCodeLocalDevRoute
  AppModesCodeTasksRoute: typeof AppModesCodeTasksRoute
  AppModesCodeThreadsRoute: typeof AppModesCodeThreadsRoute
  AppModesCollaborationInboxRoute: typeof AppModesCollaborationInboxRoute
  AppModesCodeIndexRoute: typeof AppModesCodeIndexRoute
  AppModesCodeBrowseRangeRoute: typeof AppModesCodeBrowseRangeRoute
  AppModesCodeReviewPullRoute: typeof AppModesCodeReviewPullRoute
  AppModesCodeBrowseIndexRoute: typeof AppModesCodeBrowseIndexRoute
  AppModesCodeReviewIndexRoute: typeof AppModesCodeReviewIndexRoute
  AppModesCodeBrowseCommitShaRoute: typeof AppModesCodeBrowseCommitShaRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppModesAgentSessionRoute: AppModesAgentSessionRouteWithChildren,
  AppModesCollaborationRoute: AppModesCollaborationRoute,
  AppModesCodeBranchesRoute: AppModesCodeBranchesRoute,
  AppModesCodeCommitRoute: AppModesCodeCommitRoute,
  AppModesCodeDocsRoute: AppModesCodeDocsRoute,
  AppModesCodeHistoryRoute: AppModesCodeHistoryRoute,
  AppModesCodeLocalDevRoute: AppModesCodeLocalDevRoute,
  AppModesCodeTasksRoute: AppModesCodeTasksRoute,
  AppModesCodeThreadsRoute: AppModesCodeThreadsRoute,
  AppModesCollaborationInboxRoute: AppModesCollaborationInboxRoute,
  AppModesCodeIndexRoute: AppModesCodeIndexRoute,
  AppModesCodeBrowseRangeRoute: AppModesCodeBrowseRangeRoute,
  AppModesCodeReviewPullRoute: AppModesCodeReviewPullRoute,
  AppModesCodeBrowseIndexRoute: AppModesCodeBrowseIndexRoute,
  AppModesCodeReviewIndexRoute: AppModesCodeReviewIndexRoute,
  AppModesCodeBrowseCommitShaRoute: AppModesCodeBrowseCommitShaRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  KitchenSinkRoute: KitchenSinkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
