/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as KitchenSinkRouteImport } from './routes/kitchen-sink'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as WorkspaceSettingsRouteImport } from './routes/_workspace/settings'
import { Route as WorkspaceModesAgentSessionRouteImport } from './routes/_workspace/modes.agent-session'
import { Route as WorkspaceModesCollaborationRouteImport } from './routes/_workspace/modes.collaboration'
import { Route as AppModesCodeIndexRouteImport } from './routes/_app/modes.code.index'
import { Route as AppModesCodeCommitRouteImport } from './routes/_app/modes.code.commit'
import { Route as WorkspaceModesAgentSessionIndexRouteImport } from './routes/_workspace/modes.agent-session.index'
import { Route as WorkspaceModesAgentSessionChatIdRouteImport } from './routes/_workspace/modes.agent-session.$chatId'
import { Route as WorkspaceModesCodeCommentsRouteImport } from './routes/_workspace/modes.code.comments'
import { Route as WorkspaceModesCodeDocsRouteImport } from './routes/_workspace/modes.code.docs'
import { Route as WorkspaceModesCodeLocalDevRouteImport } from './routes/_workspace/modes.code.local-dev'
import { Route as WorkspaceModesCodeTasksRouteImport } from './routes/_workspace/modes.code.tasks'
import { Route as WorkspaceModesCodeThreadsRouteImport } from './routes/_workspace/modes.code.threads'
import { Route as WorkspaceModesCollaborationInboxRouteImport } from './routes/_workspace/modes.collaboration_.inbox'
import { Route as AppModesCodeBrowseIndexRouteImport } from './routes/_app/modes.code.browse.index'
import { Route as AppModesCodeBrowseRangeRouteImport } from './routes/_app/modes.code.browse.range'
import { Route as AppModesCodeReviewIndexRouteImport } from './routes/_app/modes.code.review.index'
import { Route as AppModesCodeReviewPullRouteImport } from './routes/_app/modes.code.review.$pull'
import { Route as AppModesCodeBrowseCommitShaRouteImport } from './routes/_app/modes.code.browse.commit.$sha'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenSinkRoute = KitchenSinkRouteImport.update({
  id: '/kitchen-sink',
  path: '/kitchen-sink',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceModesAgentSessionRoute =
  WorkspaceModesAgentSessionRouteImport.update({
    id: '/modes/agent-session',
    path: '/modes/agent-session',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceModesCollaborationRoute =
  WorkspaceModesCollaborationRouteImport.update({
    id: '/modes/collaboration',
    path: '/modes/collaboration',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const AppModesCodeIndexRoute = AppModesCodeIndexRouteImport.update({
  id: '/modes/code/',
  path: '/modes/code/',
  getParentRoute: () => AppRoute,
} as any)
const AppModesCodeCommitRoute = AppModesCodeCommitRouteImport.update({
  id: '/modes/code/commit',
  path: '/modes/code/commit',
  getParentRoute: () => AppRoute,
} as any)
const WorkspaceModesAgentSessionIndexRoute =
  WorkspaceModesAgentSessionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceModesAgentSessionRoute,
  } as any)
const WorkspaceModesAgentSessionChatIdRoute =
  WorkspaceModesAgentSessionChatIdRouteImport.update({
    id: '/$chatId',
    path: '/$chatId',
    getParentRoute: () => WorkspaceModesAgentSessionRoute,
  } as any)
const WorkspaceModesCodeCommentsRoute =
  WorkspaceModesCodeCommentsRouteImport.update({
    id: '/modes/code/comments',
    path: '/modes/code/comments',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceModesCodeDocsRoute = WorkspaceModesCodeDocsRouteImport.update({
  id: '/modes/code/docs',
  path: '/modes/code/docs',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceModesCodeLocalDevRoute =
  WorkspaceModesCodeLocalDevRouteImport.update({
    id: '/modes/code/local-dev',
    path: '/modes/code/local-dev',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceModesCodeTasksRoute = WorkspaceModesCodeTasksRouteImport.update({
  id: '/modes/code/tasks',
  path: '/modes/code/tasks',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceModesCodeThreadsRoute =
  WorkspaceModesCodeThreadsRouteImport.update({
    id: '/modes/code/threads',
    path: '/modes/code/threads',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceModesCollaborationInboxRoute =
  WorkspaceModesCollaborationInboxRouteImport.update({
    id: '/modes/collaboration_/inbox',
    path: '/modes/collaboration/inbox',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const AppModesCodeBrowseIndexRoute = AppModesCodeBrowseIndexRouteImport.update({
  id: '/modes/code/browse/',
  path: '/modes/code/browse/',
  getParentRoute: () => AppRoute,
} as any)
const AppModesCodeBrowseRangeRoute = AppModesCodeBrowseRangeRouteImport.update({
  id: '/modes/code/browse/range',
  path: '/modes/code/browse/range',
  getParentRoute: () => AppRoute,
} as any)
const AppModesCodeReviewIndexRoute = AppModesCodeReviewIndexRouteImport.update({
  id: '/modes/code/review/',
  path: '/modes/code/review/',
  getParentRoute: () => AppRoute,
} as any)
const AppModesCodeReviewPullRoute = AppModesCodeReviewPullRouteImport.update({
  id: '/modes/code/review/$pull',
  path: '/modes/code/review/$pull',
  getParentRoute: () => AppRoute,
} as any)
const AppModesCodeBrowseCommitShaRoute =
  AppModesCodeBrowseCommitShaRouteImport.update({
    id: '/modes/code/browse/commit/$sha',
    path: '/modes/code/browse/commit/$sha',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/kitchen-sink': typeof KitchenSinkRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/modes/agent-session': typeof WorkspaceModesAgentSessionRouteWithChildren
  '/modes/collaboration': typeof WorkspaceModesCollaborationRoute
  '/modes/code/commit': typeof AppModesCodeCommitRoute
  '/modes/agent-session/$chatId': typeof WorkspaceModesAgentSessionChatIdRoute
  '/modes/code/comments': typeof WorkspaceModesCodeCommentsRoute
  '/modes/code/docs': typeof WorkspaceModesCodeDocsRoute
  '/modes/code/local-dev': typeof WorkspaceModesCodeLocalDevRoute
  '/modes/code/tasks': typeof WorkspaceModesCodeTasksRoute
  '/modes/code/threads': typeof WorkspaceModesCodeThreadsRoute
  '/modes/collaboration/inbox': typeof WorkspaceModesCollaborationInboxRoute
  '/modes/code/': typeof AppModesCodeIndexRoute
  '/modes/agent-session/': typeof WorkspaceModesAgentSessionIndexRoute
  '/modes/code/browse/range': typeof AppModesCodeBrowseRangeRoute
  '/modes/code/review/$pull': typeof AppModesCodeReviewPullRoute
  '/modes/code/browse/': typeof AppModesCodeBrowseIndexRoute
  '/modes/code/review/': typeof AppModesCodeReviewIndexRoute
  '/modes/code/browse/commit/$sha': typeof AppModesCodeBrowseCommitShaRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/kitchen-sink': typeof KitchenSinkRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/modes/collaboration': typeof WorkspaceModesCollaborationRoute
  '/modes/code/commit': typeof AppModesCodeCommitRoute
  '/modes/agent-session/$chatId': typeof WorkspaceModesAgentSessionChatIdRoute
  '/modes/code/comments': typeof WorkspaceModesCodeCommentsRoute
  '/modes/code/docs': typeof WorkspaceModesCodeDocsRoute
  '/modes/code/local-dev': typeof WorkspaceModesCodeLocalDevRoute
  '/modes/code/tasks': typeof WorkspaceModesCodeTasksRoute
  '/modes/code/threads': typeof WorkspaceModesCodeThreadsRoute
  '/modes/collaboration/inbox': typeof WorkspaceModesCollaborationInboxRoute
  '/modes/code': typeof AppModesCodeIndexRoute
  '/modes/agent-session': typeof WorkspaceModesAgentSessionIndexRoute
  '/modes/code/browse/range': typeof AppModesCodeBrowseRangeRoute
  '/modes/code/review/$pull': typeof AppModesCodeReviewPullRoute
  '/modes/code/browse': typeof AppModesCodeBrowseIndexRoute
  '/modes/code/review': typeof AppModesCodeReviewIndexRoute
  '/modes/code/browse/commit/$sha': typeof AppModesCodeBrowseCommitShaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/kitchen-sink': typeof KitchenSinkRoute
  '/_workspace/settings': typeof WorkspaceSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_workspace/modes/agent-session': typeof WorkspaceModesAgentSessionRouteWithChildren
  '/_workspace/modes/collaboration': typeof WorkspaceModesCollaborationRoute
  '/_app/modes/code/commit': typeof AppModesCodeCommitRoute
  '/_workspace/modes/agent-session/$chatId': typeof WorkspaceModesAgentSessionChatIdRoute
  '/_workspace/modes/code/comments': typeof WorkspaceModesCodeCommentsRoute
  '/_workspace/modes/code/docs': typeof WorkspaceModesCodeDocsRoute
  '/_workspace/modes/code/local-dev': typeof WorkspaceModesCodeLocalDevRoute
  '/_workspace/modes/code/tasks': typeof WorkspaceModesCodeTasksRoute
  '/_workspace/modes/code/threads': typeof WorkspaceModesCodeThreadsRoute
  '/_workspace/modes/collaboration_/inbox': typeof WorkspaceModesCollaborationInboxRoute
  '/_app/modes/code/': typeof AppModesCodeIndexRoute
  '/_workspace/modes/agent-session/': typeof WorkspaceModesAgentSessionIndexRoute
  '/_app/modes/code/browse/range': typeof AppModesCodeBrowseRangeRoute
  '/_app/modes/code/review/$pull': typeof AppModesCodeReviewPullRoute
  '/_app/modes/code/browse/': typeof AppModesCodeBrowseIndexRoute
  '/_app/modes/code/review/': typeof AppModesCodeReviewIndexRoute
  '/_app/modes/code/browse/commit/$sha': typeof AppModesCodeBrowseCommitShaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kitchen-sink'
    | '/settings'
    | '/modes/agent-session'
    | '/modes/collaboration'
    | '/modes/code/commit'
    | '/modes/agent-session/$chatId'
    | '/modes/code/comments'
    | '/modes/code/docs'
    | '/modes/code/local-dev'
    | '/modes/code/tasks'
    | '/modes/code/threads'
    | '/modes/collaboration/inbox'
    | '/modes/code/'
    | '/modes/agent-session/'
    | '/modes/code/browse/range'
    | '/modes/code/review/$pull'
    | '/modes/code/browse/'
    | '/modes/code/review/'
    | '/modes/code/browse/commit/$sha'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kitchen-sink'
    | '/settings'
    | '/modes/collaboration'
    | '/modes/code/commit'
    | '/modes/agent-session/$chatId'
    | '/modes/code/comments'
    | '/modes/code/docs'
    | '/modes/code/local-dev'
    | '/modes/code/tasks'
    | '/modes/code/threads'
    | '/modes/collaboration/inbox'
    | '/modes/code'
    | '/modes/agent-session'
    | '/modes/code/browse/range'
    | '/modes/code/review/$pull'
    | '/modes/code/browse'
    | '/modes/code/review'
    | '/modes/code/browse/commit/$sha'
  id:
    | '__root__'
    | '/_app'
    | '/_workspace'
    | '/kitchen-sink'
    | '/_workspace/settings'
    | '/_app/'
    | '/_workspace/modes/agent-session'
    | '/_workspace/modes/collaboration'
    | '/_app/modes/code/commit'
    | '/_workspace/modes/agent-session/$chatId'
    | '/_workspace/modes/code/comments'
    | '/_workspace/modes/code/docs'
    | '/_workspace/modes/code/local-dev'
    | '/_workspace/modes/code/tasks'
    | '/_workspace/modes/code/threads'
    | '/_workspace/modes/collaboration_/inbox'
    | '/_app/modes/code/'
    | '/_workspace/modes/agent-session/'
    | '/_app/modes/code/browse/range'
    | '/_app/modes/code/review/$pull'
    | '/_app/modes/code/browse/'
    | '/_app/modes/code/review/'
    | '/_app/modes/code/browse/commit/$sha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  KitchenSinkRoute: typeof KitchenSinkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-sink': {
      id: '/kitchen-sink'
      path: '/kitchen-sink'
      fullPath: '/kitchen-sink'
      preLoaderRoute: typeof KitchenSinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_workspace/settings': {
      id: '/_workspace/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/modes/agent-session': {
      id: '/_workspace/modes/agent-session'
      path: '/modes/agent-session'
      fullPath: '/modes/agent-session'
      preLoaderRoute: typeof WorkspaceModesAgentSessionRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/modes/collaboration': {
      id: '/_workspace/modes/collaboration'
      path: '/modes/collaboration'
      fullPath: '/modes/collaboration'
      preLoaderRoute: typeof WorkspaceModesCollaborationRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_app/modes/code/': {
      id: '/_app/modes/code/'
      path: '/modes/code'
      fullPath: '/modes/code/'
      preLoaderRoute: typeof AppModesCodeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modes/code/commit': {
      id: '/_app/modes/code/commit'
      path: '/modes/code/commit'
      fullPath: '/modes/code/commit'
      preLoaderRoute: typeof AppModesCodeCommitRouteImport
      parentRoute: typeof AppRoute
    }
    '/_workspace/modes/agent-session/': {
      id: '/_workspace/modes/agent-session/'
      path: '/'
      fullPath: '/modes/agent-session/'
      preLoaderRoute: typeof WorkspaceModesAgentSessionIndexRouteImport
      parentRoute: typeof WorkspaceModesAgentSessionRoute
    }
    '/_workspace/modes/agent-session/$chatId': {
      id: '/_workspace/modes/agent-session/$chatId'
      path: '/$chatId'
      fullPath: '/modes/agent-session/$chatId'
      preLoaderRoute: typeof WorkspaceModesAgentSessionChatIdRouteImport
      parentRoute: typeof WorkspaceModesAgentSessionRoute
    }
    '/_workspace/modes/code/comments': {
      id: '/_workspace/modes/code/comments'
      path: '/modes/code/comments'
      fullPath: '/modes/code/comments'
      preLoaderRoute: typeof WorkspaceModesCodeCommentsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/modes/code/docs': {
      id: '/_workspace/modes/code/docs'
      path: '/modes/code/docs'
      fullPath: '/modes/code/docs'
      preLoaderRoute: typeof WorkspaceModesCodeDocsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/modes/code/local-dev': {
      id: '/_workspace/modes/code/local-dev'
      path: '/modes/code/local-dev'
      fullPath: '/modes/code/local-dev'
      preLoaderRoute: typeof WorkspaceModesCodeLocalDevRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/modes/code/tasks': {
      id: '/_workspace/modes/code/tasks'
      path: '/modes/code/tasks'
      fullPath: '/modes/code/tasks'
      preLoaderRoute: typeof WorkspaceModesCodeTasksRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/modes/code/threads': {
      id: '/_workspace/modes/code/threads'
      path: '/modes/code/threads'
      fullPath: '/modes/code/threads'
      preLoaderRoute: typeof WorkspaceModesCodeThreadsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/modes/collaboration_/inbox': {
      id: '/_workspace/modes/collaboration_/inbox'
      path: '/modes/collaboration/inbox'
      fullPath: '/modes/collaboration/inbox'
      preLoaderRoute: typeof WorkspaceModesCollaborationInboxRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_app/modes/code/browse/': {
      id: '/_app/modes/code/browse/'
      path: '/modes/code/browse'
      fullPath: '/modes/code/browse/'
      preLoaderRoute: typeof AppModesCodeBrowseIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modes/code/browse/range': {
      id: '/_app/modes/code/browse/range'
      path: '/modes/code/browse/range'
      fullPath: '/modes/code/browse/range'
      preLoaderRoute: typeof AppModesCodeBrowseRangeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modes/code/review/': {
      id: '/_app/modes/code/review/'
      path: '/modes/code/review'
      fullPath: '/modes/code/review/'
      preLoaderRoute: typeof AppModesCodeReviewIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modes/code/review/$pull': {
      id: '/_app/modes/code/review/$pull'
      path: '/modes/code/review/$pull'
      fullPath: '/modes/code/review/$pull'
      preLoaderRoute: typeof AppModesCodeReviewPullRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modes/code/browse/commit/$sha': {
      id: '/_app/modes/code/browse/commit/$sha'
      path: '/modes/code/browse/commit/$sha'
      fullPath: '/modes/code/browse/commit/$sha'
      preLoaderRoute: typeof AppModesCodeBrowseCommitShaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppModesCodeCommitRoute: typeof AppModesCodeCommitRoute
  AppModesCodeIndexRoute: typeof AppModesCodeIndexRoute
  AppModesCodeBrowseRangeRoute: typeof AppModesCodeBrowseRangeRoute
  AppModesCodeReviewPullRoute: typeof AppModesCodeReviewPullRoute
  AppModesCodeBrowseIndexRoute: typeof AppModesCodeBrowseIndexRoute
  AppModesCodeReviewIndexRoute: typeof AppModesCodeReviewIndexRoute
  AppModesCodeBrowseCommitShaRoute: typeof AppModesCodeBrowseCommitShaRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppModesCodeCommitRoute: AppModesCodeCommitRoute,
  AppModesCodeIndexRoute: AppModesCodeIndexRoute,
  AppModesCodeBrowseRangeRoute: AppModesCodeBrowseRangeRoute,
  AppModesCodeReviewPullRoute: AppModesCodeReviewPullRoute,
  AppModesCodeBrowseIndexRoute: AppModesCodeBrowseIndexRoute,
  AppModesCodeReviewIndexRoute: AppModesCodeReviewIndexRoute,
  AppModesCodeBrowseCommitShaRoute: AppModesCodeBrowseCommitShaRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface WorkspaceModesAgentSessionRouteChildren {
  WorkspaceModesAgentSessionChatIdRoute: typeof WorkspaceModesAgentSessionChatIdRoute
  WorkspaceModesAgentSessionIndexRoute: typeof WorkspaceModesAgentSessionIndexRoute
}

const WorkspaceModesAgentSessionRouteChildren: WorkspaceModesAgentSessionRouteChildren =
  {
    WorkspaceModesAgentSessionChatIdRoute:
      WorkspaceModesAgentSessionChatIdRoute,
    WorkspaceModesAgentSessionIndexRoute: WorkspaceModesAgentSessionIndexRoute,
  }

const WorkspaceModesAgentSessionRouteWithChildren =
  WorkspaceModesAgentSessionRoute._addFileChildren(
    WorkspaceModesAgentSessionRouteChildren,
  )

interface WorkspaceRouteChildren {
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRoute
  WorkspaceModesAgentSessionRoute: typeof WorkspaceModesAgentSessionRouteWithChildren
  WorkspaceModesCollaborationRoute: typeof WorkspaceModesCollaborationRoute
  WorkspaceModesCodeCommentsRoute: typeof WorkspaceModesCodeCommentsRoute
  WorkspaceModesCodeDocsRoute: typeof WorkspaceModesCodeDocsRoute
  WorkspaceModesCodeLocalDevRoute: typeof WorkspaceModesCodeLocalDevRoute
  WorkspaceModesCodeTasksRoute: typeof WorkspaceModesCodeTasksRoute
  WorkspaceModesCodeThreadsRoute: typeof WorkspaceModesCodeThreadsRoute
  WorkspaceModesCollaborationInboxRoute: typeof WorkspaceModesCollaborationInboxRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceSettingsRoute: WorkspaceSettingsRoute,
  WorkspaceModesAgentSessionRoute: WorkspaceModesAgentSessionRouteWithChildren,
  WorkspaceModesCollaborationRoute: WorkspaceModesCollaborationRoute,
  WorkspaceModesCodeCommentsRoute: WorkspaceModesCodeCommentsRoute,
  WorkspaceModesCodeDocsRoute: WorkspaceModesCodeDocsRoute,
  WorkspaceModesCodeLocalDevRoute: WorkspaceModesCodeLocalDevRoute,
  WorkspaceModesCodeTasksRoute: WorkspaceModesCodeTasksRoute,
  WorkspaceModesCodeThreadsRoute: WorkspaceModesCodeThreadsRoute,
  WorkspaceModesCollaborationInboxRoute: WorkspaceModesCollaborationInboxRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  KitchenSinkRoute: KitchenSinkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
