/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as KitchenSinkRouteImport } from './routes/kitchen-sink'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppCommitRouteImport } from './routes/_app/commit'
import { Route as WorkspaceChatsRouteImport } from './routes/_workspace/chats'
import { Route as WorkspaceCommentsRouteImport } from './routes/_workspace/comments'
import { Route as WorkspaceDocsRouteImport } from './routes/_workspace/docs'
import { Route as WorkspaceLocalDevRouteImport } from './routes/_workspace/local-dev'
import { Route as WorkspaceSettingsRouteImport } from './routes/_workspace/settings'
import { Route as WorkspaceTasksRouteImport } from './routes/_workspace/tasks'
import { Route as WorkspaceThreadsRouteImport } from './routes/_workspace/threads'
import { Route as AppBrowseIndexRouteImport } from './routes/_app/browse/index'
import { Route as AppBrowseRangeRouteImport } from './routes/_app/browse/range'
import { Route as AppReviewIndexRouteImport } from './routes/_app/review/index'
import { Route as AppReviewPullRouteImport } from './routes/_app/review/$pull'
import { Route as WorkspaceChatsIndexRouteImport } from './routes/_workspace/chats.index'
import { Route as WorkspaceChatsChatIdRouteImport } from './routes/_workspace/chats.$chatId'
import { Route as AppBrowseCommitShaRouteImport } from './routes/_app/browse/commit.$sha'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenSinkRoute = KitchenSinkRouteImport.update({
  id: '/kitchen-sink',
  path: '/kitchen-sink',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCommitRoute = AppCommitRouteImport.update({
  id: '/commit',
  path: '/commit',
  getParentRoute: () => AppRoute,
} as any)
const WorkspaceChatsRoute = WorkspaceChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceCommentsRoute = WorkspaceCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDocsRoute = WorkspaceDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceLocalDevRoute = WorkspaceLocalDevRouteImport.update({
  id: '/local-dev',
  path: '/local-dev',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceTasksRoute = WorkspaceTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceThreadsRoute = WorkspaceThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => WorkspaceRoute,
} as any)
const AppBrowseIndexRoute = AppBrowseIndexRouteImport.update({
  id: '/browse/',
  path: '/browse/',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowseRangeRoute = AppBrowseRangeRouteImport.update({
  id: '/browse/range',
  path: '/browse/range',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewIndexRoute = AppReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewPullRoute = AppReviewPullRouteImport.update({
  id: '/review/$pull',
  path: '/review/$pull',
  getParentRoute: () => AppRoute,
} as any)
const WorkspaceChatsIndexRoute = WorkspaceChatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceChatsRoute,
} as any)
const WorkspaceChatsChatIdRoute = WorkspaceChatsChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => WorkspaceChatsRoute,
} as any)
const AppBrowseCommitShaRoute = AppBrowseCommitShaRouteImport.update({
  id: '/browse/commit/$sha',
  path: '/browse/commit/$sha',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/kitchen-sink': typeof KitchenSinkRoute
  '/commit': typeof AppCommitRoute
  '/chats': typeof WorkspaceChatsRouteWithChildren
  '/comments': typeof WorkspaceCommentsRoute
  '/docs': typeof WorkspaceDocsRoute
  '/local-dev': typeof WorkspaceLocalDevRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/tasks': typeof WorkspaceTasksRoute
  '/threads': typeof WorkspaceThreadsRoute
  '/browse/range': typeof AppBrowseRangeRoute
  '/review/$pull': typeof AppReviewPullRoute
  '/chats/$chatId': typeof WorkspaceChatsChatIdRoute
  '/browse/': typeof AppBrowseIndexRoute
  '/review/': typeof AppReviewIndexRoute
  '/chats/': typeof WorkspaceChatsIndexRoute
  '/browse/commit/$sha': typeof AppBrowseCommitShaRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/kitchen-sink': typeof KitchenSinkRoute
  '/commit': typeof AppCommitRoute
  '/comments': typeof WorkspaceCommentsRoute
  '/docs': typeof WorkspaceDocsRoute
  '/local-dev': typeof WorkspaceLocalDevRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/tasks': typeof WorkspaceTasksRoute
  '/threads': typeof WorkspaceThreadsRoute
  '/browse/range': typeof AppBrowseRangeRoute
  '/review/$pull': typeof AppReviewPullRoute
  '/chats/$chatId': typeof WorkspaceChatsChatIdRoute
  '/browse': typeof AppBrowseIndexRoute
  '/review': typeof AppReviewIndexRoute
  '/chats': typeof WorkspaceChatsIndexRoute
  '/browse/commit/$sha': typeof AppBrowseCommitShaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/kitchen-sink': typeof KitchenSinkRoute
  '/_app/commit': typeof AppCommitRoute
  '/_workspace/chats': typeof WorkspaceChatsRouteWithChildren
  '/_workspace/comments': typeof WorkspaceCommentsRoute
  '/_workspace/docs': typeof WorkspaceDocsRoute
  '/_workspace/local-dev': typeof WorkspaceLocalDevRoute
  '/_workspace/settings': typeof WorkspaceSettingsRoute
  '/_workspace/tasks': typeof WorkspaceTasksRoute
  '/_workspace/threads': typeof WorkspaceThreadsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/browse/range': typeof AppBrowseRangeRoute
  '/_app/review/$pull': typeof AppReviewPullRoute
  '/_workspace/chats/$chatId': typeof WorkspaceChatsChatIdRoute
  '/_app/browse/': typeof AppBrowseIndexRoute
  '/_app/review/': typeof AppReviewIndexRoute
  '/_workspace/chats/': typeof WorkspaceChatsIndexRoute
  '/_app/browse/commit/$sha': typeof AppBrowseCommitShaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kitchen-sink'
    | '/commit'
    | '/chats'
    | '/comments'
    | '/docs'
    | '/local-dev'
    | '/settings'
    | '/tasks'
    | '/threads'
    | '/browse/range'
    | '/review/$pull'
    | '/chats/$chatId'
    | '/browse/'
    | '/review/'
    | '/chats/'
    | '/browse/commit/$sha'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kitchen-sink'
    | '/commit'
    | '/comments'
    | '/docs'
    | '/local-dev'
    | '/settings'
    | '/tasks'
    | '/threads'
    | '/browse/range'
    | '/review/$pull'
    | '/chats/$chatId'
    | '/browse'
    | '/review'
    | '/chats'
    | '/browse/commit/$sha'
  id:
    | '__root__'
    | '/_app'
    | '/_workspace'
    | '/kitchen-sink'
    | '/_app/commit'
    | '/_workspace/chats'
    | '/_workspace/comments'
    | '/_workspace/docs'
    | '/_workspace/local-dev'
    | '/_workspace/settings'
    | '/_workspace/tasks'
    | '/_workspace/threads'
    | '/_app/'
    | '/_app/browse/range'
    | '/_app/review/$pull'
    | '/_workspace/chats/$chatId'
    | '/_app/browse/'
    | '/_app/review/'
    | '/_workspace/chats/'
    | '/_app/browse/commit/$sha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  KitchenSinkRoute: typeof KitchenSinkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-sink': {
      id: '/kitchen-sink'
      path: '/kitchen-sink'
      fullPath: '/kitchen-sink'
      preLoaderRoute: typeof KitchenSinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/commit': {
      id: '/_app/commit'
      path: '/commit'
      fullPath: '/commit'
      preLoaderRoute: typeof AppCommitRouteImport
      parentRoute: typeof AppRoute
    }
    '/_workspace/chats': {
      id: '/_workspace/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof WorkspaceChatsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/comments': {
      id: '/_workspace/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof WorkspaceCommentsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/docs': {
      id: '/_workspace/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof WorkspaceDocsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/local-dev': {
      id: '/_workspace/local-dev'
      path: '/local-dev'
      fullPath: '/local-dev'
      preLoaderRoute: typeof WorkspaceLocalDevRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/settings': {
      id: '/_workspace/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/tasks': {
      id: '/_workspace/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof WorkspaceTasksRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/threads': {
      id: '/_workspace/threads'
      path: '/threads'
      fullPath: '/threads'
      preLoaderRoute: typeof WorkspaceThreadsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_app/browse/': {
      id: '/_app/browse/'
      path: '/browse'
      fullPath: '/browse/'
      preLoaderRoute: typeof AppBrowseIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse/range': {
      id: '/_app/browse/range'
      path: '/browse/range'
      fullPath: '/browse/range'
      preLoaderRoute: typeof AppBrowseRangeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review/': {
      id: '/_app/review/'
      path: '/review'
      fullPath: '/review/'
      preLoaderRoute: typeof AppReviewIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review/$pull': {
      id: '/_app/review/$pull'
      path: '/review/$pull'
      fullPath: '/review/$pull'
      preLoaderRoute: typeof AppReviewPullRouteImport
      parentRoute: typeof AppRoute
    }
    '/_workspace/chats/': {
      id: '/_workspace/chats/'
      path: '/'
      fullPath: '/chats/'
      preLoaderRoute: typeof WorkspaceChatsIndexRouteImport
      parentRoute: typeof WorkspaceChatsRoute
    }
    '/_workspace/chats/$chatId': {
      id: '/_workspace/chats/$chatId'
      path: '/$chatId'
      fullPath: '/chats/$chatId'
      preLoaderRoute: typeof WorkspaceChatsChatIdRouteImport
      parentRoute: typeof WorkspaceChatsRoute
    }
    '/_app/browse/commit/$sha': {
      id: '/_app/browse/commit/$sha'
      path: '/browse/commit/$sha'
      fullPath: '/browse/commit/$sha'
      preLoaderRoute: typeof AppBrowseCommitShaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCommitRoute: typeof AppCommitRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBrowseRangeRoute: typeof AppBrowseRangeRoute
  AppReviewPullRoute: typeof AppReviewPullRoute
  AppBrowseIndexRoute: typeof AppBrowseIndexRoute
  AppReviewIndexRoute: typeof AppReviewIndexRoute
  AppBrowseCommitShaRoute: typeof AppBrowseCommitShaRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCommitRoute: AppCommitRoute,
  AppIndexRoute: AppIndexRoute,
  AppBrowseRangeRoute: AppBrowseRangeRoute,
  AppReviewPullRoute: AppReviewPullRoute,
  AppBrowseIndexRoute: AppBrowseIndexRoute,
  AppReviewIndexRoute: AppReviewIndexRoute,
  AppBrowseCommitShaRoute: AppBrowseCommitShaRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface WorkspaceChatsRouteChildren {
  WorkspaceChatsChatIdRoute: typeof WorkspaceChatsChatIdRoute
  WorkspaceChatsIndexRoute: typeof WorkspaceChatsIndexRoute
}

const WorkspaceChatsRouteChildren: WorkspaceChatsRouteChildren = {
  WorkspaceChatsChatIdRoute: WorkspaceChatsChatIdRoute,
  WorkspaceChatsIndexRoute: WorkspaceChatsIndexRoute,
}

const WorkspaceChatsRouteWithChildren = WorkspaceChatsRoute._addFileChildren(
  WorkspaceChatsRouteChildren,
)

interface WorkspaceRouteChildren {
  WorkspaceChatsRoute: typeof WorkspaceChatsRouteWithChildren
  WorkspaceCommentsRoute: typeof WorkspaceCommentsRoute
  WorkspaceDocsRoute: typeof WorkspaceDocsRoute
  WorkspaceLocalDevRoute: typeof WorkspaceLocalDevRoute
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRoute
  WorkspaceTasksRoute: typeof WorkspaceTasksRoute
  WorkspaceThreadsRoute: typeof WorkspaceThreadsRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceChatsRoute: WorkspaceChatsRouteWithChildren,
  WorkspaceCommentsRoute: WorkspaceCommentsRoute,
  WorkspaceDocsRoute: WorkspaceDocsRoute,
  WorkspaceLocalDevRoute: WorkspaceLocalDevRoute,
  WorkspaceSettingsRoute: WorkspaceSettingsRoute,
  WorkspaceTasksRoute: WorkspaceTasksRoute,
  WorkspaceThreadsRoute: WorkspaceThreadsRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  KitchenSinkRoute: KitchenSinkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
