import * as Context from "effect/Context"
import * as Effect from "effect/Effect"
import { agentCommand } from "../../threads/functions/agents.ts"
import type { GitFailure } from "../../../ports/git-exec.ts"
import { GitExec } from "../../../ports/git-exec.ts"
import { TerminalError, TerminalExec } from "../../../ports/terminal-exec.ts"
import type { CommitAgent } from "../schema/git-message.schema.ts"

const MAX_DIFF_CHARS = 16000
export const DEFAULT_COMMIT_AGENT: CommitAgent = "claude"
const branchSlug = (branch: string): string | null => {
  const match = branch.match(/[A-Z][A-Z0-9]*-\d+/)
  return match?.[0] ?? null
}
const buildPrompt = (changes: string, slug: string | null): string =>
  [
    "Generate a git commit message for the changes below.",
    "",
    "Rules:",
    "- First line: a concise, descriptive title summarizing the change.",
    "- Then a blank line, then bullet points (each starting with '- ')",
    "  describing the notable changes.",
    "- Be descriptive and factual. Do not be flamboyant or use marketing language.",
    '- Do NOT include any attribution ("Generated by", "Co-Authored-By", tool or',
    "  model names).",
    "- Do NOT add a Conventional Commits prefix (no feat:/fix:/chore:/refactor:/etc.).",
    slug !== null
      ? `- Begin the title with "${slug} " (the issue slug), then the summary.`
      : "- Do not add any prefix to the title.",
    "",
    "Output ONLY the raw commit message — no surrounding quotes, no markdown code",
    "fences, no preamble or sign-off.",
    "",
    "--- CHANGES ---",
    changes,
  ].join("\n")
const cleanMessage = (raw: string): string => {
  let text = raw.trim()
  const fence = text.match(/^```[^\n]*\n([\s\S]*?)\n```$/)
  if (fence?.[1] !== undefined) text = fence[1].trim()
  if (
    text.length >= 2 &&
    ((text.startsWith('"') && text.endsWith('"')) ||
      (text.startsWith("'") && text.endsWith("'")))
  ) {
    text = text.slice(1, -1).trim()
  }
  return text
}
export interface GitMessageServiceShape {
  readonly generate: (
    paths: ReadonlyArray<string>,
    agent: CommitAgent
  ) => Effect.Effect<string, GitFailure | TerminalError>
}
export class GitMessageService extends Context.Service<
  GitMessageService,
  GitMessageServiceShape
>()("GitMessageService") {}
export const makeGitMessageService = Effect.gen(function* () {
  const { lines, run } = yield* GitExec
  const terminal = yield* TerminalExec
  const generate: GitMessageServiceShape["generate"] = (paths, agent) =>
    Effect.gen(function* () {
      const diff = yield* run(
        ...(paths.length === 0
          ? ["diff", "HEAD"]
          : ["diff", "HEAD", "--", ...paths])
      ).pipe(Effect.catchTag("GitError", () => Effect.succeed("")))
      const untracked = yield* lines(
        ...(paths.length === 0
          ? ["ls-files", "--others", "--exclude-standard"]
          : ["ls-files", "--others", "--exclude-standard", "--", ...paths])
      ).pipe(Effect.catchTag("GitError", () => Effect.succeed([] as const)))
      const truncated =
        diff.length > MAX_DIFF_CHARS
          ? `${diff.slice(0, MAX_DIFF_CHARS)}\n…[diff truncated]`
          : diff
      const newFiles =
        untracked.length > 0
          ? `\n\nNew untracked files:\n${untracked.map((f) => `  ${f}`).join("\n")}`
          : ""
      const changes = `${truncated}${newFiles}`.trim()
      if (changes.length === 0) {
        return yield* Effect.fail(
          new TerminalError({ reason: "no changes to summarize" })
        )
      }
      const branch = yield* run("rev-parse", "--abbrev-ref", "HEAD").pipe(
        Effect.map((b) => b.trim()),
        Effect.catchTag("GitError", () => Effect.succeed(""))
      )
      const prompt = buildPrompt(changes, branchSlug(branch))
      const { stdout, stderr, exitCode } = yield* terminal.run(
        agentCommand(agent, prompt)
      )
      if (exitCode !== 0) {
        const reason = stderr.trim()
        return yield* Effect.fail(
          new TerminalError({
            reason:
              reason.length > 0
                ? `the "${agent}" CLI exited ${exitCode}: ${reason}`
                : `the "${agent}" CLI exited ${exitCode} — is it installed and on your PATH?`,
          })
        )
      }
      const message = cleanMessage(stdout)
      return message.length > 0
        ? message
        : yield* Effect.fail(
            new TerminalError({
              reason: `the "${agent}" CLI produced no commit message`,
            })
          )
    })
  return GitMessageService.of({ generate })
})
