/**
 * Writes `src/render/fileIconRules.generated.ts`: the rules and hues the SPA
 * tree and the Mac sidebar use to pick a file's icon, read from the same
 * sources as `packages/mac-os/scripts/import-file-icons.mjs`. Re-run after
 * bumping `@pierre/trees` or editing the SPA's hue or extra-icon tables:
 *
 *   bun scripts/importFileIcons.ts
 */
import { HUE, hueOf } from '../../spa/src/components/ui/file-type-hues';
import { EXTRA_EXTENSION_TOKENS } from '../../spa/src/components/ui/file-type-extra-icons';
import { TOKEN_GLYPHS } from '../src/render/fileIconGlyphs';

const trees = new URL('../../spa/node_modules/@pierre/trees/', import.meta.url);
const output = new URL(
  '../src/render/fileIconRules.generated.ts',
  import.meta.url,
);

const { version } = (await Bun.file(new URL('package.json', trees)).json()) as {
  version: string;
};
const rulesSource = await Bun.file(
  new URL('dist/builtInIcons.js', trees),
).text();

const byFileName = lowerKeys(table('BUILT_IN_FILE_NAME_TOKENS'));
const byExtension = lowerKeys({
  ...table('BUILT_IN_FILE_EXTENSION_TOKENS'),
  ...EXTRA_EXTENSION_TOKENS,
});
const extensionOverrides = lowerKeys(table('COMPLETE_EXTENSION_OVERRIDES'));

const tokens = [
  ...new Set([
    'default',
    ...Object.values(byFileName),
    ...Object.values(byExtension),
    ...Object.values(extensionOverrides),
  ]),
].sort();
const unglyphed = tokens.filter((token) => !(token in TOKEN_GLYPHS));
if (unglyphed.length > 0)
  throw new Error(`no glyph in fileIconGlyphs.ts for ${unglyphed.join(', ')}`);

const tokenHues = Object.fromEntries(
  tokens.map((token) => [token, hueOf(token)]),
);

await Bun.write(
  output,
  `// Generated by scripts/importFileIcons.ts from @pierre/trees ${version} and
// the SPA's file-type-hues.ts and file-type-extra-icons.ts — do not edit.

/** Each hue, light then dark. */
export const HUES = ${literal(HUE)} as const satisfies Record<string, readonly [string, string]>;

export type HueName = keyof typeof HUES;

export const TOKEN_HUES: Record<string, HueName> = ${literal(tokenHues)};

/** By the whole file name, lower-cased. */
export const BY_FILE_NAME: Record<string, string> = ${literal(byFileName)};

/** By extension, longest candidate first. */
export const BY_EXTENSION: Record<string, string> = ${literal(byExtension)};

/** The complete set's picks over the standard ones — React for tsx. */
export const EXTENSION_OVERRIDES: Record<string, string> = ${literal(extensionOverrides)};
`,
);
Bun.spawnSync(['bunx', 'prettier', '--write', output.pathname]);
console.log(
  `wrote ${output.pathname}: ${tokens.length} tokens, ${Object.keys(byFileName).length} names, ${Object.keys(byExtension).length} extensions`,
);

/** The rules are module-private in the package, so they are lifted from its source. */
function table(name: string): Record<string, string> {
  const match = rulesSource.match(
    new RegExp(`const ${name} = (\\{[\\s\\S]*?\\n\\});`),
  );
  if (!match) throw new Error(`${name} not found in @pierre/trees`);
  return Function(`return ${match[1]}`)() as Record<string, string>;
}

function lowerKeys(record: Record<string, string>): Record<string, string> {
  return Object.fromEntries(
    Object.entries(record).map(([key, value]) => [key.toLowerCase(), value]),
  );
}

function literal(record: Record<string, unknown>): string {
  const sorted = Object.fromEntries(
    Object.entries(record).sort(([a], [b]) => (a < b ? -1 : 1)),
  );
  return JSON.stringify(sorted, null, 2);
}
