import JSZip from "jszip";
import type { BrandConfig, LayoutKind } from "./config";
import { PRESETS } from "./config";
import type { OutlinedText } from "./font";
import { buildScene } from "./geometry";
import { formatSvg, renderSvg } from "./svg";
import { ICO_SIZES, encodeIco, rasterize } from "./raster";

export const MARK_PNG_SIZES = [16, 32, 48, 64, 128, 180, 192, 256, 512, 1024];
const LOCKUP_PNG_WIDTHS = [512, 1024, 2048];

const LAYOUTS: Array<LayoutKind> = [
  "mark",
  "horizontal",
  "stacked",
  "wordmark",
];

type Variant = { id: string; layout: LayoutKind; config: BrandConfig };

/** Colour variants worth shipping for each layout — the rest are one click away. */
const VARIANTS_BY_LAYOUT: Record<LayoutKind, Array<string>> = {
  mark: [
    "dark",
    "light",
    "dark-gradient",
    "light-gradient",
    "tile",
    "mono",
    "mono-inverse",
  ],
  horizontal: ["dark", "light", "dark-gradient", "mono", "mono-inverse"],
  stacked: ["dark", "light", "dark-gradient", "mono", "mono-inverse"],
  wordmark: ["mono", "mono-inverse"],
};

function variants(base: BrandConfig): Array<Variant> {
  return LAYOUTS.flatMap((layout) =>
    VARIANTS_BY_LAYOUT[layout].flatMap((presetId) => {
      const preset = PRESETS.find((candidate) => candidate.id === presetId);
      if (!preset) return [];
      return [
        {
          id: `${layout}-${presetId}`,
          layout,
          config: { ...base, ...preset.config, layout },
        },
      ];
    })
  );
}

export type PackProgress = { done: number; total: number; label: string };

export async function buildAssetPack(
  base: BrandConfig,
  text: OutlinedText | null,
  onProgress: (progress: PackProgress) => void
) {
  const zip = new JSZip();
  const all = variants(base);
  const rasterJobs = all.filter(
    (variant) => variant.layout !== "wordmark"
  ).length;
  const total = all.length + rasterJobs + 1;
  let done = 0;
  const step = (label: string) => onProgress({ done: ++done, total, label });

  const sceneFor = (variant: Variant) => buildScene(variant.config, text);

  for (const variant of all) {
    const scene = sceneFor(variant);
    const svg = renderSvg(scene, variant.config, {
      title: `Reviewer — ${variant.id}`,
    });
    zip.file(`svg/reviewer-${variant.id}.svg`, formatSvg(svg));
    step(`svg/reviewer-${variant.id}.svg`);
  }

  for (const variant of all) {
    if (variant.layout === "wordmark") continue;
    const scene = sceneFor(variant);
    const svg = renderSvg(scene, variant.config);
    const widths =
      variant.layout === "mark"
        ? MARK_PNG_SIZES
        : LOCKUP_PNG_WIDTHS.slice(0, variant.layout === "stacked" ? 2 : 3);

    for (const width of widths) {
      const height = Math.round((width * scene.height) / scene.width);
      const blob = await rasterize(svg, width, height);
      const name =
        variant.layout === "mark"
          ? `png/${variant.layout}/reviewer-${variant.id}-${width}.png`
          : `png/${variant.layout}/reviewer-${variant.id}-${width}w.png`;
      zip.file(name, blob);
    }
    step(`png/${variant.layout}/reviewer-${variant.id}`);
  }

  const favicon = all.find((variant) => variant.id === "mark-dark") ?? all[0];
  if (favicon) {
    const scene = sceneFor(favicon);
    const svg = renderSvg(scene, favicon.config);
    const pngs = await Promise.all(
      ICO_SIZES.map(async (size) => ({
        size,
        bytes: await (await rasterize(svg, size, size)).arrayBuffer(),
      }))
    );
    zip.file("favicon.ico", await encodeIco(pngs));
    zip.file("apple-touch-icon.png", await rasterize(svg, 180, 180));
  }
  step("favicon.ico");

  zip.file("README.md", readme(base));
  return zip.generateAsync({ type: "blob" });
}

function readme(config: BrandConfig) {
  return [
    "# Reviewer brand assets",
    "",
    "Generated by `packages/brand` — re-run the studio to regenerate at different settings.",
    "",
    "- `svg/` — source-of-truth vectors. The wordmark is outlined, so no font is needed.",
    "- `png/mark/` — square icon at every size an app store, OS or browser asks for.",
    "- `png/horizontal/`, `png/stacked/` — lockups, named by pixel width.",
    "- `favicon.ico` — multi-resolution icon (16–256px).",
    "- `apple-touch-icon.png` — 180px, for iOS home screens.",
    "",
    "## Settings used",
    "",
    `- Wordmark: ${config.wordmark}`,
    `- Typeface: Space Grotesk ${config.fontWeight}`,
    `- Tile radius: ${Math.round(config.tileRadius * 100)}%`,
    `- Block radius: ${Math.round(config.blockRadius * 100)}%`,
    `- Block gap: ${Math.round(config.blockGap * 100)}%`,
    `- Mark padding: ${Math.round(config.markPadding * 100)}%`,
    "",
  ].join("\n");
}
