import { build } from "esbuild"
import { mkdir, writeFile } from "node:fs/promises"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const entry = join(here, "../src/index.ts")
const out = join(here, "../src/bundle.generated.ts")

const result = await build({
  entryPoints: [entry],
  bundle: true,
  format: "iife",
  target: "es2022",
  platform: "browser",
  minify: true,
  write: false,
  legalComments: "none",
})

const [file] = result.outputFiles
if (file === undefined) throw new Error("esbuild produced no output")

await mkdir(dirname(out), { recursive: true })
await writeFile(
  out,
  `// Generated by scripts/build.ts — do not edit.\nexport const PICKER_BUNDLE = ${JSON.stringify(file.text)}\n`
)

console.log(`picker bundle: ${(file.text.length / 1024).toFixed(1)} kB`)
