import type { HueName } from './fileIconRules.generated';

/**
 * A Nerd Font glyph for each of the Mac tree's icon tokens, picked from
 * nvim-web-devicons and kept to glyphs Nerd Fonts 3.0 already ships.
 */
export const TOKEN_GLYPHS: Record<string, string> = {
  astro: '\u{f14de}',
  babel: '\u{e639}',
  bash: '\u{e795}',
  biome: '\u{f032a}',
  blade: '\u{e73f}',
  bootstrap: '\u{e747}',
  browserslist: '\u{f059f}',
  bun: '\u{e76f}',
  c: '\u{e61e}',
  claude: '\u{f0674}',
  cpp: '\u{e61d}',
  css: '\u{e749}',
  database: '\u{e706}',
  default: '\u{f15b}',
  docker: '\u{f0868}',
  eslint: '\u{e655}',
  font: '\u{f031}',
  git: '\u{e702}',
  go: '\u{e627}',
  graphql: '\u{f20e}',
  html: '\u{e736}',
  image: '\u{e60d}',
  javascript: '\u{e60c}',
  json: '\u{e60b}',
  markdown: '\u{f48a}',
  mcp: '\u{f06a5}',
  nextjs: '\u{f0537}',
  npm: '\u{e71e}',
  oxc: '\u{f45e}',
  php: '\u{e608}',
  postcss: '\u{e749}',
  prettier: '\u{f03d8}',
  python: '\u{e606}',
  react: '\u{e7ba}',
  ruby: '\u{e791}',
  rust: '\u{e68b}',
  sass: '\u{e603}',
  stylelint: '\u{e749}',
  svelte: '\u{e697}',
  svg: '\u{f0721}',
  svgo: '\u{f0721}',
  swift: '\u{e755}',
  table: '\u{e64a}',
  tailwind: '\u{f13ff}',
  terraform: '\u{e69a}',
  text: '\u{f0219}',
  typescript: '\u{e628}',
  vite: '\u{f140b}',
  vscode: '\u{e70c}',
  vue: '\u{e6a0}',
  wasm: '\u{e6a1}',
  webpack: '\u{f072b}',
  yml: '\u{e615}',
  zig: '\u{e6a9}',
  zip: '\u{f410}',
};

export interface ExtraIcon {
  glyph: string;
  hue: HueName;
}

/** Types the Mac tree leaves on the plain document, which a terminal can still tell apart. */
export const EXTRA_BY_EXTENSION: Record<string, ExtraIcon> = {
  bat: { glyph: '\u{e795}', hue: 'green' },
  clj: { glyph: '\u{e768}', hue: 'green' },
  cs: { glyph: '\u{f031b}', hue: 'indigo' },
  dart: { glyph: '\u{e798}', hue: 'blue' },
  elm: { glyph: '\u{e62c}', hue: 'cyan' },
  erl: { glyph: '\u{e7b1}', hue: 'pink' },
  ex: { glyph: '\u{e62d}', hue: 'purple' },
  exs: { glyph: '\u{e62d}', hue: 'purple' },
  flac: { glyph: '\u{f0386}', hue: 'teal' },
  gradle: { glyph: '\u{e660}', hue: 'teal' },
  hs: { glyph: '\u{e61f}', hue: 'purple' },
  java: { glyph: '\u{e738}', hue: 'red' },
  jl: { glyph: '\u{e624}', hue: 'purple' },
  kt: { glyph: '\u{e634}', hue: 'indigo' },
  kts: { glyph: '\u{e634}', hue: 'indigo' },
  lock: { glyph: '\u{e672}', hue: 'gray' },
  lua: { glyph: '\u{e620}', hue: 'blue' },
  ml: { glyph: '\u{e67a}', hue: 'orange' },
  mov: { glyph: '\u{f022b}', hue: 'orange' },
  mp3: { glyph: '\u{f0386}', hue: 'teal' },
  mp4: { glyph: '\u{f022b}', hue: 'orange' },
  nim: { glyph: '\u{e677}', hue: 'yellow' },
  nix: { glyph: '\u{f313}', hue: 'blue' },
  pdf: { glyph: '\u{f1c1}', hue: 'red' },
  pl: { glyph: '\u{e769}', hue: 'blue' },
  ps1: { glyph: '\u{f0a0a}', hue: 'blue' },
  r: { glyph: '\u{f07d4}', hue: 'blue' },
  scala: { glyph: '\u{e737}', hue: 'red' },
  sol: { glyph: '\u{e656}', hue: 'blue' },
  tex: { glyph: '\u{e69b}', hue: 'green' },
  toml: { glyph: '\u{e6b2}', hue: 'orange' },
  vim: { glyph: '\u{e62b}', hue: 'green' },
  wav: { glyph: '\u{f0386}', hue: 'teal' },
  webm: { glyph: '\u{f022b}', hue: 'orange' },
  xml: { glyph: '\u{f05c0}', hue: 'orange' },
};

export const EXTRA_BY_FILE_NAME: Record<string, ExtraIcon> = {
  'cmakelists.txt': { glyph: '\u{e794}', hue: 'gray' },
  gemfile: { glyph: '\u{e791}', hue: 'red' },
  'go.mod': { glyph: '\u{e627}', hue: 'cyan' },
  'go.sum': { glyph: '\u{e627}', hue: 'cyan' },
  license: { glyph: '\u{e60a}', hue: 'yellow' },
  makefile: { glyph: '\u{e779}', hue: 'gray' },
  rakefile: { glyph: '\u{e791}', hue: 'red' },
};

export const FOLDER_GLYPH = { open: '\u{e5fe}', closed: '\u{e5ff}' };
